# Generated by Django 5.2.6 on 2025-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=25)),
                ('idade', models.IntegerField(max_length=3)),
                ('dataNascimento', models.DateField()),
                ('dataIngresso', models.DateField()),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
    ]
